#!/bin/bash

TEMPLATE_PATH="$HOME/Library/Developer/Xcode/Templates"
# TEMPLATE_PATH="./t/Templates"
BEEFRAMEWORK="BeeFramework"
TEMPLATE_FILE="File Templates"
TEMPLATE_PROJECT="Project Templates"
TEMPLATE_FILE_PATH="$TEMPLATE_PATH/$TEMPLATE_FILE"
TEMPLATE_PROJECT_PATH="$TEMPLATE_PATH/$TEMPLATE_PROJECT"
SOURCE_TEMPLATE="./Templates"
SOURCE_TEMPLATE_FILE="$SOURCE_TEMPLATE/$TEMPLATE_FILE/$BEEFRAMEWORK"
SOURCE_TEMPLATE_PROJECT="$SOURCE_TEMPLATE/$TEMPLATE_PROJECT/$BEEFRAMEWORK"

# # 如果已有，先删除上一个版本的
if [ -d "$TEMPLATE_FILE_PATH/$BEEFRAMEWORK" ]; then
  sudo rm -rf "$TEMPLATE_FILE_PATH/$BEEFRAMEWORK"
  echo "remove $TEMPLATE_FILE_PATH/$BEEFRAMEWORK"
fi

if [ -d "$TEMPLATE_PROJECT_PATH/$BEEFRAMEWORK" ]; then
  sudo rm -rf "$TEMPLATE_PROJECT_PATH/$BEEFRAMEWORK"
  echo "remove $TEMPLATE_PROJECT_PATH/$BEEFRAMEWORK"
fi

echo "Bee Xcode Template is uninstalled. 
Have a nice Day~"
